name: Streamlit - Deploy to Hugging Face

on:
  push:
    paths:
      - '06_Streamlit/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Install Git LFS
      - name: Install Git LFS
        run: |
          git lfs install
          git lfs track "06_Streamlit/src/images/*.png"
          git add .gitattributes
          git commit -m "Track images with LFS" || echo "No changes to commit"

      # 3️⃣ Push to Hugging Face
      - name: Push to Hugging Face with LFS
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          mkdir tmp
          cp -r 06_Streamlit/* tmp/
          cd tmp

          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # LFS setup dans tmp
          git lfs install
          git lfs track "src/images/*.png"
          git add .gitattributes
          git add src/images/*.png
          git add .
          git commit -m "Deploy to HF with LFS"

          git branch -M main
          git remote add hf "https://lyx51:${HF_TOKEN}@huggingface.co/spaces/lyx51/Housing-Price-Estimator-Streamlit"

          # 4️⃣ Push LFS objects d'abord
          git lfs push hf main

          # 5️⃣ Puis push normal
          git push hf main --force